"""
AGENT 3 — Writer Agent

Role:
Synthesize analysed_data + raw_signals into a high-quality, structured weekly
revenue intelligence briefing in markdown.

Output is strictly formatted with the five required sections:
1. Executive Summary
2. Market Signals
3. Internal Performance
4. Anomalies & Risks
5. Recommended Actions

This is the deliverable that gets sent via WhatsApp + Email.
"""

from __future__ import annotations

import logging
import time
import uuid
from datetime import datetime
from typing import Any

import anthropic

from src.config.settings import get_settings
from src.database.connection import db_session
from src.database.models import RunLog

logger = logging.getLogger(__name__)
settings = get_settings()


WRITER_PROMPT = """You are an elite revenue operations writer for a fast-growing B2B industrial equipment company in India.

You are given:
- Structured anomalies and recommendations from the Analyst Agent
- Raw external market signals
- Internal performance data summaries

Write a crisp, executive-grade weekly briefing in Markdown.

STRICT FORMAT (use these exact H2 headers in order):

# Weekly Revenue Intelligence Briefing
**Week of {date}** | Generated by Multi-Agent RevOps Orchestrator

## 1. Executive Summary
(3-5 bullets. One sentence each. Lead with the single most important insight.)

## 2. Market Signals
(Bullet list of the most relevant external signals. Include competitor name, what happened, and why it matters. Max 6 bullets.)

## 3. Internal Performance
(Short narrative + 1-2 small tables if data is rich. Highlight Tier-A dealers and any clear winners/laggards.)

## 4. Anomalies & Risks
(Use the anomalies array from the Analyst. For each, state severity, affected parties, and quantified impact where available.)

## 5. Recommended Actions
(Numbered list. Every action must have: owner, timeframe, and priority. Pull directly from the Analyst's recommended_actions.)

TONE: Professional, direct, data-driven, action-oriented. No fluff. No "we recommend considering..." — say "Action: X should do Y by Z date."

Return ONLY the markdown. No JSON wrapper, no extra commentary.
"""


class WriterAgent:
    """Produces the final structured briefing markdown."""

    def __init__(self, anthropic_client: anthropic.Anthropic | None = None):
        self.client = anthropic_client or anthropic.Anthropic(api_key=settings.anthropic_api_key)
        self.model = settings.claude_model

    def _log(self, run_id: uuid.UUID, status: str, details: str, duration_ms: int | None = None) -> None:
        if not settings.enable_state_logging:
            return
        try:
            with db_session() as db:
                db.add(RunLog(run_id=run_id, node_name="writer", status=status, output_summary=details[:1500], execution_time_ms=duration_ms))
        except Exception:
            pass

    def write_briefing(
        self,
        analysed_data: dict[str, Any],
        raw_signals: list[dict[str, Any]],
        run_id: uuid.UUID | None = None,
    ) -> dict[str, Any]:
        run_id = run_id or uuid.uuid4()
        start = time.time()
        self._log(run_id, "started", "Generating structured briefing")

        date_str = datetime.utcnow().strftime("%d %b %Y")
        anomalies = analysed_data.get("anomalies", [])
        recommendations = analysed_data.get("recommended_actions", [])
        strategic = analysed_data.get("strategic_summary", "")

        signals_bullets = "\n".join(
            f"- **{s.get('competitor', 'Market')}** ({s.get('signal_type')}): {s.get('summary', '')}"
            for s in raw_signals[:6]
        ) or "- No high-relevance external signals captured this week."

        prompt = WRITER_PROMPT.format(date=date_str) + f"""

ANALYST OUTPUT (structured):
Strategic Summary: {strategic}

Anomalies:
{anomalies}

Recommended Actions:
{recommendations}

RAW EXTERNAL SIGNALS (for reference):
{signals_bullets}

Now produce the full markdown briefing following the exact 5-section structure.
"""

        try:
            resp = self.client.messages.create(
                model=self.model,
                max_tokens=3200,
                temperature=0.25,
                messages=[{"role": "user", "content": prompt}],
            )
            markdown = resp.content[0].text.strip() if resp.content else "# Weekly Revenue Intelligence Briefing\n\n*No content generated.*"

            # Guarantee the five sections exist
            required = ["Executive Summary", "Market Signals", "Internal Performance", "Anomalies & Risks", "Recommended Actions"]
            for section in required:
                if section not in markdown:
                    markdown += f"\n\n## {section}\n*Data for this section was not generated in this run.*\n"

            duration = int((time.time() - start) * 1000)
            self._log(run_id, "success", f"Briefing generated ({len(markdown)} chars)", duration)

            return {
                "briefing_draft": markdown,
                "writer_completed_at": datetime.utcnow().isoformat(),
                "word_count": len(markdown.split()),
            }

        except Exception as e:
            duration = int((time.time() - start) * 1000)
            self._log(run_id, "failed", str(e), duration)
            fallback = f"""# Weekly Revenue Intelligence Briefing
**Week of {date_str}**

## 1. Executive Summary
- System encountered an error during briefing generation.
- Manual review of latest revenue data and market signals is recommended.
- Run ID: {run_id}

## 5. Recommended Actions
1. Investigate Writer Agent failure (RevOps Engineering, this week, P0)
"""
            return {"briefing_draft": fallback, "error": str(e)}


async def run_writer(analysed_data: dict, raw_signals: list[dict], run_id: uuid.UUID | None = None) -> dict[str, Any]:
    agent = WriterAgent()
    return agent.write_briefing(analysed_data, raw_signals, run_id)
